### ISSUE TITLE
How to make usb patch for laptop thunderbolt 3 port ?

### ISSUE THREAD

**Issue by Jamesxxx1997** [Sniki/OS-X-USB-Inject-All#4]
Hi , I have a laptop [thinkpad x1 yoga 2018](https://www.tonymacx86.com/threads/guide-thinkpad-x1-yoga-3rd-gen-20ld-with-mojave.261823/) , with two **thunderbolt3\type c** USB port , but idk how to make thunderbolt 3 port patch on laptop ; is there any guide about it ? 
Thank you.

**Comment by Sniki** [comment]
Hi @Jamesxxx1997 USB Ports configuration is a different thing and has nothing to do with Thunderbolt,
USB-C Ports can be configured but idk about thunderbolt and how to configure them as it has nothing to do with USBInjectAll and i have no Thunderbolt hardware to test and work on it.
