### ISSUE TITLE
Inconsistent injection of high current properties

### ISSUE THREAD

**Issue by f00b4r0** [Sniki/OS-X-USB-Inject-All#8]
Hi,

I don't know if this is a USBInjectAll bug or an OpenCore bug: I recently migrated from Clover to OpenCore 0.5.9, and at the same time I upgraded to USBInjectAll 0.7.5 using the build referenced here https://github.com/Sniki/OS-X-USB-Inject-All/issues/7#issuecomment-612630485

I'm running Mojave 10.14.6 (18G5033) on an ASUS Z370 Prime-A (rev1) / i3-8350k, SMBIOS iMac19,1

When I boot the machine, every now and then the USB ports will not deliver the extra current as configured in SSDT-USBX

Sometimes it will work correctly, sometimes the ports will be limited to the USB2 or USB3 'standard' max (500 or 900mA), even though in all cases ACPI/_SB/USBX@0 is present and seemingly correctly populated in IORegistryExplorer. When it doesn't work, in System Information -> Hardware -> USB, for each device Available Sleep Current is not displayed and Extra Operating Current is displayed but remains 0 no matter what is plugged.

I haven't been able to identify what causes this problem, it's a hit-and-miss: I have to reboot multiple times until the extra current becomes effectively available.

This problem did not occur with Clover and USBInjectAll 0.7.1 (last RehabMan version) with SMBIOS iMac18,3 (which I was using prior to the migration)

**Comment by Sniki** [comment]
> Hi,
> 
> I don't know if this is a USBInjectAll bug or an OpenCore bug: I recently migrated from Clover to OpenCore 0.5.9, and at the same time I upgraded to USBInjectAll 0.7.5 using the build referenced here [#7 (comment)](https://github.com/Sniki/OS-X-USB-Inject-All/issues/7#issuecomment-612630485)
> 
> I'm running Mojave 10.14.6 (18G5033) on an ASUS Z370 Prime-A (rev1) / i3-8350k, SMBIOS iMac19,1
> 
> When I boot the machine, every now and then the USB ports will not deliver the extra current as configured in SSDT-USBX
> 
> Sometimes it will work correctly, sometimes the ports will be limited to the USB2 or USB3 'standard' max (500 or 900mA), even though in all cases ACPI/_SB/USBX@0 is present and seemingly correctly populated in IORegistryExplorer. When it doesn't work, in System Information -> Hardware -> USB, for each device Available Sleep Current is not displayed and Extra Operating Current is displayed but remains 0 no matter what is plugged.
> 
> I haven't been able to identify what causes this problem, it's a hit-and-miss: I have to reboot multiple times until the extra current becomes effectively available.
> 
> This problem did not occur with Clover and USBInjectAll 0.7.1 (last RehabMan version) with SMBIOS iMac18,3 (which I was using prior to the migration)

Maybe you should try the debugging version and check logs if you can spot any message related to USB.

Or simply try the rehabman version instead and check if that same situation happens.

**Comment by f00b4r0** [comment]
Hi, sorry I forgot about this. This is not a UIA issue eventually, I was able to reproduce with USBmap. It seems to affect 10.14 but not 10.15: since I upgraded everything works as intended.

FWIW, I noticed in 10.14 verbose boot messages like these: 
```
AppleBusPowerController: ApplePowerController::requestStaticServicePowerLocked: power supply unavailable, assuming successful power for SS06 of 750 mWWakePower and 0 mWSleepPower
AppleBusPowerController: ApplePowerController::requestStaticServicePowerLocked: power supply unavailable, assuming successful power for SS05 of 2500 mWWakePower and 0 mWSleepPower
AppleBusPowerController: AppleBusPowerController::requestStaticServicePowerLocked: power supply unavailable, assuming successful power for AppleUSB20HubPort of 500mWWakePower and 0mWSleepPower
```

That's with OpenCore and some devices plugged during boot. These messages are gone in 10.15 (still OpenCore) and USB high power / sleep power works fine there.

Anyway, apologies for not closing this earlier.
